CREATE TABLE IF NOT EXISTS workspaces (id SERIAL PRIMARY KEY, notion_workspace_id TEXT UNIQUE NOT NULL, name TEXT NOT NULL, icon TEXT DEFAULT '◈', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sources (id SERIAL PRIMARY KEY, workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, notion_page_id TEXT NOT NULL, title TEXT NOT NULL, last_synced_at TIMESTAMPTZ, UNIQUE(workspace_id, notion_page_id));
CREATE TABLE IF NOT EXISTS quizzes (id SERIAL PRIMARY KEY, source_id INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE, title TEXT NOT NULL, question_count INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS questions (id SERIAL PRIMARY KEY, quiz_id INTEGER NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE, position INTEGER NOT NULL, type TEXT NOT NULL CHECK(type IN ('multiple_choice','true_false','short_answer')), prompt TEXT NOT NULL, choices JSONB NOT NULL DEFAULT '[]', correct_answer TEXT NOT NULL, explanation TEXT NOT NULL DEFAULT '', source_excerpt TEXT NOT NULL DEFAULT '', task_key TEXT);
CREATE TABLE IF NOT EXISTS attempts (id SERIAL PRIMARY KEY, quiz_id INTEGER NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE, started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completed_at TIMESTAMPTZ, score INTEGER, total_questions INTEGER NOT NULL, mode TEXT NOT NULL DEFAULT 'normal');
CREATE TABLE IF NOT EXISTS attempt_answers (id SERIAL PRIMARY KEY, attempt_id INTEGER NOT NULL REFERENCES attempts(id) ON DELETE CASCADE, question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE, given_answer TEXT NOT NULL, is_correct BOOLEAN NOT NULL, answered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(attempt_id, question_id));
CREATE TABLE IF NOT EXISTS attempt_task_results (id SERIAL PRIMARY KEY, attempt_id INTEGER NOT NULL REFERENCES attempts(id) ON DELETE CASCADE, task_key TEXT NOT NULL, correct_count INTEGER NOT NULL, total_questions INTEGER NOT NULL, score INTEGER NOT NULL, UNIQUE(attempt_id, task_key));
CREATE TABLE IF NOT EXISTS notion_sync_requests (id SERIAL PRIMARY KEY, attempt_id INTEGER NOT NULL REFERENCES attempts(id) ON DELETE CASCADE, status TEXT NOT NULL DEFAULT 'queued', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completed_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_quizzes_source_created ON quizzes(source_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attempts_quiz ON attempts(quiz_id, started_at DESC);

INSERT INTO workspaces (notion_workspace_id, name, icon) VALUES ('demo-product','Product notes','✦'),('demo-learning','Learning lab','◒') ON CONFLICT DO NOTHING;
INSERT INTO sources (workspace_id, notion_page_id, title, last_synced_at)
SELECT id, 'page-product-principles', 'Product principles', NOW() FROM workspaces WHERE notion_workspace_id='demo-product' ON CONFLICT DO NOTHING;
INSERT INTO sources (workspace_id, notion_page_id, title, last_synced_at)
SELECT id, 'page-systems-thinking', 'Systems thinking', NOW() FROM workspaces WHERE notion_workspace_id='demo-learning' ON CONFLICT DO NOTHING;
INSERT INTO quizzes (source_id, title, question_count)
SELECT id, 'Product principles · Quick check', 5 FROM sources WHERE notion_page_id='page-product-principles' AND NOT EXISTS (SELECT 1 FROM quizzes WHERE title='Product principles · Quick check');
INSERT INTO quizzes (source_id, title, question_count)
SELECT id, 'Systems thinking · Foundations', 5 FROM sources WHERE notion_page_id='page-systems-thinking' AND NOT EXISTS (SELECT 1 FROM quizzes WHERE title='Systems thinking · Foundations');
INSERT INTO questions (quiz_id, position, type, prompt, choices, correct_answer, explanation, source_excerpt)
SELECT q.id, x.position, 'multiple_choice', x.prompt, x.choices::jsonb, x.answer, x.explanation, x.excerpt
FROM quizzes q CROSS JOIN (VALUES
 (1,'What is the strongest signal that a product principle is useful?','["It sounds memorable","It helps a team make a difficult tradeoff","It appears on a homepage","It is approved by leadership"]','It helps a team make a difficult tradeoff','A principle earns its place when it guides a decision under pressure, not when it simply sounds polished.','Principles are decision tools, especially when priorities conflict.'),
 (2,'Which behavior best protects a team from solving the wrong problem?','["Ship faster","Write more tickets","Spend time with the people experiencing the problem","Add more dashboards"]','Spend time with the people experiencing the problem','Direct observation and conversations reveal the gap between the stated request and the underlying need.','Start with the lived problem before choosing a solution.'),
 (3,'True or false: A small experiment can be valuable even when it does not prove the final solution.','["True","False"]','True','Experiments reduce uncertainty. Learning what does not work is still useful evidence.','Use small tests to learn before making a large commitment.'),
 (4,'What should a team do when two principles point in different directions?','["Ignore both","Choose the louder stakeholder","Make the tradeoff explicit","Wait for perfect information"]','Make the tradeoff explicit','Naming the tension makes the decision legible and creates a shared rationale.','Good principles do not remove tradeoffs; they make them easier to discuss.'),
 (5,'True or false: A principle should be specific enough to change an actual decision.','["True","False"]','True','If a principle cannot affect behavior, it is closer to a slogan than a working principle.','The test of a principle is whether it changes what the team does next.')
) AS x(position,prompt,choices,answer,explanation,excerpt) WHERE q.title='Product principles · Quick check' AND NOT EXISTS (SELECT 1 FROM questions WHERE quiz_id=q.id);
INSERT INTO questions (quiz_id, position, type, prompt, choices, correct_answer, explanation, source_excerpt)
SELECT q.id, x.position, 'multiple_choice', x.prompt, x.choices::jsonb, x.answer, x.explanation, x.excerpt
FROM quizzes q CROSS JOIN (VALUES
 (1,'What is a useful first move when looking at a complex system?','["Map its parts and relationships","Optimize one metric","Pick a single cause","Remove all feedback loops"]','Map its parts and relationships','A map gives you a shared view of actors, dependencies, and feedback before you intervene.','Understand relationships, not only components.'),
 (2,'True or false: Delays can make a system hard to understand because effects appear after the cause.','["True","False"]','True','Time delays hide causality and can lead to overcorrection.','Watch for delays between action and outcome.'),
 (3,'Which pattern often creates unintended growth?','["A reinforcing feedback loop","A fixed boundary","A single observation","A static label"]','A reinforcing feedback loop','Reinforcing loops amplify change, which can produce rapid growth or decline.','Feedback loops explain how small changes can compound.'),
 (4,'What is a leverage point?','["A place where a small change can shift system behavior","A point on a chart","A project deadline","A team meeting"]','A place where a small change can shift system behavior','Leverage points are places where an intervention can produce disproportionate effects.','Look for structure and rules that shape behavior.'),
 (5,'True or false: Optimizing a part always improves the whole system.','["True","False"]','False','Local optimization can damage the larger system when parts have competing goals or hidden dependencies.','The whole system may behave differently from its parts.')
) AS x(position,prompt,choices,answer,explanation,excerpt) WHERE q.title='Systems thinking · Foundations' AND NOT EXISTS (SELECT 1 FROM questions WHERE quiz_id=q.id);
